services:
  postgres:
    image: postgres:15
    container_name: taskmanager-db
    restart: unless-sttoped

    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

    ports:
      - "5432:5432"

    volumes:
      - taskmanager_data:/var/lib/postgresql/data
volumes:


  